version: 0.0
os: linux
files:
  - source: /
    destination: /FlyReliablyChromeExtension
hooks:
  BeforeInstall:
    - location: scripts/no-op.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/no-op.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/no-op.sh
    - location: scripts/no-op.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/no-op.sh
      timeout: 300
      runas: root
